language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: Jia4l8WBkuqbErPyY3DqSR0V1fgrzO3AVrgDTwLwpquu8VffMkqKGVfsmz0ufMLfkB7ug3FwWHX0Qj/JJvWoKoEdJ/10E3u9yb8UtN5FY2orrQfn1uvQH30Y3suRKb1PCBTBhodSfIh+jdeNWRqhclZfuS+LZg4P3WtQCTg1CUspWKAWAZODXoD60Eyn32+EX++W7QbNToQLAuwcO2P5bA0TBkTNRG19kEoIbFpzUW3C9XyDWJ7o+7jA/98ldpJ0WNxmvviAZEgAAffeiaML5zKOpLduuO3GJWpF/eSedeJF6Q4LLnJIKfnZDbH0JXiqUniuNdH/uNtEXHVPuun8MKyXzSNEpQcTeHC8iCoEsBDfGf5i+1s/B56f6Oi4tWQNLQ89SigcDq1B2Hl/6Ro2QqpWi2ZNUuewBtW35SarjXMhnBhISzDGmdVc5ktQgxL875AQb2R2ljtwGcjlKbC10CatK6FIIIlcMi7RKNpNUUATXHicvkwvLzvrDT3i92Aj2zkPm9sXT/zu9727gcueKb3AbpmPepUg1cOGJ1Brjofgszz84WjqE//T11lqS4eF4D70HKpf5ahHWCUdkCc9cpFh7V3kONqPCsoiNzOaxY+A8Ms4Dhp8sNg/0BwbcC1t3SgNelNNFXhDwfT56N137YLFn9XFuS2tGksbAnuhHeo=
  app: stormy-dawn-37737
  on:
    all_branches: true
