language: node_js
node_js:
- '8'

script:
  - npm run build

after_success:
  - npm run deploy
  - npx semantic-release

deploy:
  - provider: surge
    project: ./dist/
    skip_cleanup: true
    domain:  alpha-abyss.surge.sh
    on:
      branch: release/alpha
  - provider: surge
    project: ./dist/
    skip_cleanup: true
    domain:  development-abyss.surge.sh
    on:
      branch: release/development