language: node_js
node_js:
- '8'

script:
  - npx semantic-release
  - npm run build

after_success:
  - npm run deploy

deploy:
  - provider: surge
    project: ./dist/
    skip_cleanup: true
    domain:  alpha-abyss.surge.sh
    on:
      branch: master